"""empty message

Revision ID: 382cb7a8e445
Revises: 
Create Date: 2022-01-05 02:20:18.811769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382cb7a8e445'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=30), nullable=True),
    sa.Column('binding', sa.String(length=20), nullable=True),
    sa.Column('publisher', sa.String(length=50), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('pubdate', sa.String(length=20), nullable=True),
    sa.Column('isbn', sa.String(length=15), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
