"""创建gift和user模型类

Revision ID: 4de9b76d42e6
Revises: 0bfdf5589ca0
Create Date: 2022-01-04 21:19:56.302553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de9b76d42e6'
down_revision = '0bfdf5589ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('status', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'status')
    # ### end Alembic commands ###
