"""添加drift模型类

Revision ID: 5720a4a14b14
Revises: aea711647449
Create Date: 2022-01-17 18:01:17.549799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5720a4a14b14'
down_revision = 'aea711647449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift',
    sa.Column('create_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=True),
    sa.Column('book_title', sa.String(length=50), nullable=True),
    sa.Column('book_author', sa.String(length=30), nullable=True),
    sa.Column('book_img', sa.String(length=50), nullable=True),
    sa.Column('gifter_id', sa.Integer(), nullable=True),
    sa.Column('gift_id', sa.Integer(), nullable=True),
    sa.Column('gifter_nickname', sa.String(length=20), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('requester_nickname', sa.String(length=20), nullable=True),
    sa.Column('pending', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drift')
    # ### end Alembic commands ###
