"""修改了book的summary字段和author字段

Revision ID: d79e303fc234
Revises: 382cb7a8e445
Create Date: 2022-01-05 03:30:13.234621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd79e303fc234'
down_revision = '382cb7a8e445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'author',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('book', 'summary',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=5000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'summary',
               existing_type=sa.String(length=5000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('book', 'author',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
