"""添加创建时间字段

Revision ID: dc949c32e0ba
Revises: cb26f6a6c76c
Create Date: 2022-01-07 17:50:53.243688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc949c32e0ba'
down_revision = 'cb26f6a6c76c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('create_time', sa.Integer(), nullable=True))
    op.add_column('gift', sa.Column('create_time', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('create_time', sa.Integer(), nullable=True))
    op.add_column('wish', sa.Column('create_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish', 'create_time')
    op.drop_column('user', 'create_time')
    op.drop_column('gift', 'create_time')
    op.drop_column('book', 'create_time')
    # ### end Alembic commands ###
